{{- if and .Values.grafana.enabled .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.grafana.service.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.grafana.ingress.host }}
      secretName: {{ .Values.grafana.service.name }}-tls
  rules:
    - host: {{ .Values.grafana.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.grafana.service.name }}
                port:
                  number: {{ .Values.grafana.service.port }}
{{- end }}
