{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grafana.service.name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.grafana.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.grafana.service.name }}
    spec:
      containers:
        - name: {{ .Values.grafana.service.name }}
          image: grafana/grafana:10.2.3
          ports:
            - containerPort: {{ .Values.grafana.service.port }}
          resources:
            requests:
              cpu: {{ .Values.grafana.limits.cpuRequests }}
              memory: {{ .Values.grafana.limits.memoryRequests }}
            limits:
              cpu: {{ .Values.grafana.limits.cpuLimits }}
              memory: {{ .Values.grafana.limits.memoryLimits }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: password
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: storage
              mountPath: /var/lib/grafana
      volumes:
        - name: datasources
          configMap:
            name: {{ .Values.grafana.service.name }}-datasources
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.grafana.service.name }}-storage
{{- end }}
