apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mediaApi.service.name }}
spec:
  replicas: {{ .Values.mediaApi.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mediaApi.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mediaApi.service.name }}
    spec:
      containers:
        - name: {{ .Values.mediaApi.service.name }}
          image: {{ index .Values.werf.image "media-api" }}
          ports:
            - containerPort: {{ .Values.mediaApi.service.portHttp }}
          resources:
            requests:
              cpu: {{ .Values.mediaApi.limits.cpuRequests }}
              memory: {{ .Values.mediaApi.limits.memoryRequests }}
            limits:
              cpu: {{ .Values.mediaApi.limits.cpuLimits }}
              memory: {{ .Values.mediaApi.limits.memoryLimits }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.mediaApi.service.portHttp }}
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.mediaApi.environment | quote }}
            - name: ConnectionStrings__Default
              valueFrom:
                secretKeyRef:
                  name: lms-db
                  key: mediaConnectionString
            - name: Keycloak__Authority
              value: {{ .Values.mediaApi.auth.issuer | quote }}
            - name: Keycloak__RequireHttpsMetadata
              value: "false"
            - name: StorageOptions__Host
              value: {{ .Values.mediaApi.s3.serviceUrl | quote }}
            - name: StorageOptions__Port
              value: {{ .Values.mediaApi.s3.port | default "80" | quote }}
            - name: StorageOptions__AccessKey
              valueFrom:
                secretKeyRef:
                  name: lms-s3
                  key: accessKey
            - name: StorageOptions__SecretKey
              valueFrom:
                secretKeyRef:
                  name: lms-s3
                  key: secretKey
            - name: StorageOptions__DefaultBucketName
              value: {{ .Values.mediaApi.s3.defaultBucketName | quote }}
            - name: StorageOptions__WithSsl
              value: {{ .Values.mediaApi.s3.withSsl | quote }}

            # Redis Configuration
            - name: RedisOptions__Host
              value: {{ .Values.mediaApi.redis.host | quote }}
            - name: RedisOptions__Port
              value: {{ .Values.mediaApi.redis.port | quote }}
            - name: RedisOptions__Password
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
