{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.service.name }}
spec:
  selector:
    app: {{ .Values.prometheus.service.name }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.port }}
      protocol: TCP
  type: ClusterIP
{{- end }}
