name: cleanup

on:
  schedule:
    - cron: "0 3 * * *"  # Every day at 3:00 AM

jobs:
  cleanup:
    name: Cleanup old images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: werf/actions/install@v2

      - name: werf cleanup
        shell: bash
        env:
          WERF_KUBECONFIG_BASE64: ${{ secrets.WERF_KUBECONFIG_BASE64 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WERF_REPO_GITHUB_TOKEN: ${{ secrets.REGISTRY_CLEANUP_TOKEN }}
        run: |
          source "$(werf ci-env github --as-file)"
          werf cleanup \
            --kube-config-base64="$WERF_KUBECONFIG_BASE64" \
            --repo-github-token="$WERF_REPO_GITHUB_TOKEN"
